[package]
name = "passes"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.bril-rs]
version = "0.1.0"
path = "../bril/bril-rs"
features = ["ssa", "memory", "float", "speculate", "position"]

